/**
 * Stockbroker directory for the Dematerialization form.
 *
 * Source: list supplied by the team (public/official emails).
 * Entries with email: "" have no on-file email — the shareholder can type
 * one in manually if they happen to know it, otherwise the request is
 * routed to the shareholder to hand-deliver to the broker themselves
 * instead of being emailed automatically.
 *
 * A few entries had small/truncated text in the source list and should be
 * spot-checked — see the "VERIFY" comments below.
 */

export const BROKERS = [
  { name: "ABSA", email: "" },
  { name: "Afrinvest Securities Limited", email: "info@afrinvestsecuritiesltd.com" },
  { name: "Anchoria Investment and Securities Limited", email: "info@anchoriaonline.com" },
  { name: "Apel Asset Limited", email: "info@apel.com.ng" }, // VERIFY: also saw "customercare@apelasset.com" listed
  { name: "APT Securities and Funds Limited", email: "info@aptsecurities.com" },
  { name: "ARM Securities Limited", email: "customerservice@armsecurities.com.ng" },
  { name: "Arthur Steven Asset Management", email: "info@arthursteven.com" },
  { name: "Associated Asset Managers Limited", email: "info@aamlng.com" },
  { name: "Atlass Portfolios Limited", email: "info@atlassportfolios.com" },
  { name: "AVA Securities Limited (formerly Helix Securities)", email: "info@avacapitalgroup.com" },
  { name: "Bauchi Investment Corp. Securities Limited", email: "info@bauchisecurities.com" },
  { name: "Belfry Investments & Securities Limited", email: "info@belfryinvestmentltd.com" },
  { name: "Bestworth Assets & Trust Limited", email: "info@bestworth-ltd.com" },
  { name: "Calyx Securities Limited", email: "info@calyxsec.com" },
  { name: "Camry Securities Limited", email: "info@camrysecuritiesng.com" },
  { name: "Capital Assets Limited", email: "info@capitalassets.com.ng" },
  { name: "Capital Bancorp Plc", email: "info@capitalbancorpgroup.com" },
  { name: "Capital Express Securities Limited", email: "info@capexng.com" },
  { name: "Capital Trust Brokers Limited", email: "info@ctb-ng.com" },
  { name: "CardinalStone Securities Limited", email: "equities@cardinalstone.com" },
  { name: "Cashcraft Securities Limited", email: "" },
  { name: "CDL Capital Markets Limited", email: "info@cdlcapitalmkts.com.ng" },
  { name: "Centre Point Investments Limited", email: "info@centrepointing.com" },
  { name: "Century Securities Limited", email: "info@centurysecuritiesng.com" },
  { name: "Chapel Hill Denham Securities Limited", email: "info@chapelhilldenham.com" },
  { name: "Chartwell Securities Limited", email: "info@chartwell.com.ng" },
  { name: "Citi Investment Capital Limited", email: "" },
  { name: "City Code Trust & Investment Company Limited", email: "info@citycodetrustlimited.com" },
  { name: "Compass Investment & Securities Limited", email: "info@compasssecurities.com" },
  { name: "Cordros Securities Limited", email: "contactcentre@cordros.com" },
  { name: "Core Securities Limited", email: "info@coresecuritiesltd.com" },
  { name: "Coronation Securities Limited", email: "crc@coronationsl.com" },
  { name: "Cowry Securities Limited", email: "info@cowryasset.com" },
  { name: "Crossworld Securities Limited", email: "info@crossworldsec.biz" },
  { name: "Crown Capital Limited", email: "info@crowncapitalng.com" },
  { name: "CSL Stockbrokers Limited", email: "cslservice@fcmb.com" },
  { name: "Deep Trust Investment Limited", email: "deeptrustinvestmentltd@yahoo.com" },
  { name: "Delords Securities Limited", email: "info@de-lords.com" },
  { name: "DLM Securities Limited", email: "info@dlm.group" },
  { name: "Dominion Trust Limited", email: "info@dominiong.com" },
  { name: "DSU Brokerage Services Limited", email: "info@dsbs.com.ng" },
  { name: "Dunbell Securities Limited", email: "info@dunbellsecuritieslimited.com" },
  { name: "Dunn Loren Merrifield Securities Limited/DLM Securities", email: "info@dlm.group" },
  { name: "Dynamic Portfolio Limited", email: "info@dynamicportfolio.com" },
  { name: "EDC Securities Limited", email: "ecobankenquiries@ecobank.com" },
  { name: "Edgefield Capital Management Limited", email: "olubode.olatunji@edgefieldng.com" },
  { name: "EFG Hermes Nigeria Limited", email: "nigeriantrading@efg-hermes.com" },
  { name: "El-Elyon Alliance & Securities Limited", email: "info@el-elyonsecurities.com" },
  { name: "Enterprise Stockbrokers Limited", email: "info@enterprisestockbrokers.com" },
  { name: "Equity Capital Solutions Limited", email: "info@equitycapitalsolution-ng.com" },
  { name: "Eurocom Securities Limited", email: "euro@eurocommsecurities.com" },
  { name: "Express Portfolio Services Limited", email: "info@expressportfolioservices.com" },
  { name: "Falcon Securities Limited", email: "info@falconseclimited.com" },
  { name: "FBC Trust & Securities Limited", email: "" },
  { name: "FBNQuest Securities Limited", email: "sec-traders@fbnquest.com" },
  { name: "FCSL Asset Management Company Limited", email: "info@fcslng.com" },
  { name: "Fidelity Finance Company Limited", email: "info@fidelityfinanceonline.com" },
  { name: "Financial & Analytics Capital Limited", email: "info@financialandanalytics.com" },
  { name: "Financial Trust Company Nigeria Limited", email: "info@financialtrustgroup.com" },
  { name: "Finmal Finance Services Limited", email: "info@finmalfinance.net" },
  { name: "First Integrated Capital Management Limited", email: "info@ficml.com" },
  { name: "FIS Securities", email: "info@fissecurities.com" },
  { name: "Foresight Securities & Investment Limited", email: "contact@foresightsecuritiesltd.com" },
  { name: "Forte Financial Limited", email: "info@fortefin.com" },
  { name: "Forthright Securities & Investments Limited", email: "info@forthrightsec.com" },
  { name: "Fortress Capital Limited", email: "info@fortresscapitalng.com" },
  { name: "FSDH Capital Limited", email: "fsdhcapital@fsdhgroup.com" },
  { name: "FSL Securities", email: "info@fsl.ng" },
  { name: "Funds Matrix & Asset Management Limited", email: "info@fundsmatrix.com.ng" },
  { name: "Fundvine Capital & Securities", email: "info@fundvinesecurities.com" }, // VERIFY: cell also listed "invest@fundvinesecurities.com"
  { name: "Futureview Securities Limited", email: "info@futureviewgroup.com" },
  { name: "GDL Stockbrokers Limited", email: "info@gdl.com.ng" },
  { name: "Gem Assets Management Limited", email: "info@gemassets.com" },
  { name: "Gidauniya Investment & Securities Limited", email: "gidauniyasecurities@yahoo.com" },
  { name: "Global Asset Management (Nigeria) Limited", email: "info@globalasset-ng.com" },
  { name: "Globalview Capital Limited", email: "info@globalviewng.com" },
  { name: "Golden Securities Limited", email: "info@goldensecuritiesltd.com" },
  { name: "Greenwich Securities Limited", email: "info@greenwichbankgroup.com" },
  { name: "Growth & Development Asset Management Limited", email: "customerservice@gdl.com.ng" },
  { name: "Gruene Capital Limited", email: "info@gruenecapital.com" },
  { name: "GTI Securities Limited", email: "headoffice@gti.com.ng" },
  { name: "Harmony Securities Limited", email: "info@harmonysecuritiesltd.com.ng" },
  { name: "Heartbeat Investments Limited", email: "info@heartbeatinvest.com" },
  { name: "Hedge Securities & Investment Co. Ltd", email: "info@hedgesecurities.com" },
  { name: "Heritage Capital Markets Limited", email: "info@heritagecapitals.com.ng" },
  { name: "ICMG Securities Limited", email: "info@icmgsecurities.com" },
  { name: "Icon Stockbrokers Limited", email: "info@iconstockbrokersltd.com" },
  { name: "Imperial Asset Managers Limited", email: "talktous@imperialasset.com.ng" },
  { name: "Integrated Trust & Investment Limited", email: "info@integratedtrustng.com" },
  { name: "Interstate Securities Limited", email: "info@interstatesecurities.com" },
  { name: "Investment One Stockbrokers International Limited", email: "info@investment-one.com" },
  { name: "Investors & Trust Company Limited", email: "info@investorsandtrust.com" },
  { name: "ITIS Securities Limited", email: "" },
  { name: "Kapital Care Trust & Investment Limited", email: "lagos@kapitalcaretrust.com" },
  { name: "Kedari Capital Limited", email: "info@kedaricapital.com" },
  { name: "Kinley Securities Limited", email: "info@kinleysecurities.com" },
  { name: "Kofana Securities & Investments Limited", email: "info@kofanasecurities.ng" },
  { name: "Kundila Finance Services Limited", email: "" },
  { name: "Lambeth Capital Limited", email: "lambethcapital@yahoo.com" },
  { name: "Lead Securities & Investment Limited", email: "assetmanagement@leadcapitalng.com" },
  { name: "Lighthouse Asset Management Limited", email: "info@lighthouse-ng.com" },
  { name: "Magnartis Finance & Investment Limited", email: "info@magnartis.com" },
  { name: "Mainstreet Bank Securities Limited", email: "info@mainstreetbanksecurities.com" },
  { name: "Marimpex Finance & Investment Company Limited", email: "" },
  { name: "Maxifund Investments & Securities Plc", email: "inquiry@maxifundplc.com" },
  { name: "MBC Securities Limited", email: "info@mbcgroup.com.ng" },
  { name: "Mega Equities Limited", email: "care@megaequities.com" },
  { name: "Meristem Stockbrokers Limited", email: "contact@meristemng.com" },
  { name: "Midas Stockbrokers Limited", email: "sam.oguntayo@midasstockbrokersltd.com" },
  { name: "Milestone Capital Management Limited", email: "info@milestone.org.ng" },
  { name: "Mission Securities Limited", email: "info@missionsecuritiesltd.com" },
  { name: "Molten Trust Limited", email: "info@moltentrust.com" },
  { name: "MORGANCAPITAL Securities Limited", email: "info@morgancapitalgroup.com" },
  { name: "Mountain Investment & Securities Limited", email: "info@mountain.com.ng" },
  { name: "Network Capital Limited", email: "info@networkcapitalltd.com" },
  { name: "Networth Securities & Finance Limited", email: "" },
  { name: "Newdevco Investment & Securities Company Limited", email: "info@newdevco.com" },
  { name: "Nigerian International Securities Limited", email: "info@nisl-ng.com" },
  { name: "Nigerian Stockbrokers Limited", email: "" },
  { name: "Norrenberger Securities Limited (formerly TFS Securities)", email: "clientservicessecurities@norrenberger.com" }, // VERIFY: cell text was cut off, may list a second address too
  { name: "Nova Finance & Securities Limited", email: "info@novafinancesecurities.com" }, // VERIFY: cell text was cut off, may list a second address too
  { name: "NOVAMBL Securities Limited", email: "info@novambl.com" },
  { name: "Osborne Capital Markets Limited", email: "info@ocmlng.com" },
  { name: "PAC Securities Limited", email: "info@pacsecurities.com" },
  { name: "Parthian Securities Limited", email: "info@parthiansecuritiesng.com" },
  { name: "Peace Capital Market Limited", email: "" },
  { name: "Pilot Securities Limited", email: "info@pilot-securities.com" },
  { name: "Pinefields Investment Service Limited", email: "info@pinefieldsltd.com" },
  { name: "PIPC Securities Limited", email: "info@pipsec.com.ng" },
  { name: "Pivot Capital Limited", email: "info@pivotcapitalltd.com" },
  { name: "Planet Capital Limited", email: "info@planetcapitalltd.com" },
  { name: "Portfolio Advisers Limited", email: "info@portfolioadvisers.com.ng" },
  { name: "Premium Capital & Stockbrokers Limited", email: "info@sfcsecurities.com" }, // VERIFY: low confidence on this pairing
  { name: "Primewealth Capital Limited", email: "info@primewealthcapital.com" },
  { name: "Prominent Securities Limited", email: "info@prominentsecurities.com" },
  { name: "PSI Securities Limited", email: "" },
  { name: "Pyramid Securities Limited", email: "" },
  { name: "Qualinvest Capital Limited/QCapital", email: "info@qualinvestcapital.com" },
  { name: "Quantum Securities Limited", email: "" },
  { name: "Quantum Zenith Securities & Investments Limited", email: "enquiries@quantumzenithsecurities.com.ng" },
  { name: "Rainbow Investment & Securities Inc. Ltd", email: "" },
  { name: "Readings Investment Limited", email: "info@readingsinvestmentsltd.com" },
  { name: "Regency Assets Management Limited", email: "info@regencyng.net" },
  { name: "RenCap Securities (Nigeria) Limited", email: "info@rencap.com" },
  { name: "Resort Securities & Trust Limited", email: "contact@resortsecurities.com" },
  { name: "Reward Investments & Services Limited", email: "info@rewardinvestments.com" },
  { name: "RMB Nigeria Stockbrokers Limited", email: "customercare@rmbstockbrokers.com" },
  { name: "Rostrum Investment & Securities Limited", email: "customercare@rostrumsec.com" },
  { name: "Rovet Capital Management Limited", email: "" },
  { name: "Royal Crest Finance Limited", email: "royalcrestfinance@yahoo.com" },
  { name: "Royal Guaranty & Trust Limited", email: "info@royalguarantytrustltd.com" },
  { name: "Royal Trust Securities Limited", email: "ndukwe.e@royaltrustsec.com" }, // VERIFY: source cell had a second address "emekandu2@gmail.com" and odd formatting
  { name: "Sankore Securities Limited", email: "compliance@sankore.com" },
  { name: "Santrust Securities Limited", email: "enquiry@santrustsecurities.com" },
  { name: "Securities Africa Limited", email: "salesng@securitiesafrica.com" },
  { name: "Securities & Capital Management Company Limited", email: "info@scmcgroup.com" },
  { name: "Shalom Investment & Financial Services Limited", email: "sifsl@shalominv.com.ng" },
  { name: "Shelong Investments Limited", email: "" },
  { name: "Sigma Securities Limited", email: "frontdesk@sigmasecurities.com.ng" },
  { name: "Signet Investments & Securities Limited", email: "info@signetng.com" },
  { name: "Skyview Capital Limited", email: "info@skyviewcapitalng.com" }, // VERIFY: cell text was cut off, may list a second (complaints@) address too
  { name: "SMADAC Securities Limited", email: "info@smadacsecuritiesltd.com" },
  { name: "Solid Rock Securities & Investment Plc", email: "info@solidrocksecng.com" },
  { name: "Spring Board Trust & Investment Limited", email: "enquiries@springboardtrustng.com" },
  { name: "Spring Trust & Securities Limited", email: "info@springtrustsec.com" },
  { name: "Stanbic IBTC Stockbrokers Limited", email: "stockbroking@stanbicibtc.com" },
  { name: "Standard Union Securities Limited", email: "office@standardun.com" },
  { name: "StoneX Financial Nigeria Limited", email: "" },
  { name: "TFS Securities & Investment Company Limited/Norrenberger Securities", email: "clientservicessecurities@norrenberger.com" },
  { name: "The Bridge Securities Limited", email: "info@thebridgesecurities.com" },
  { name: "Tiddo Securities Limited", email: "headoffice@tiddosecurities.com" },
  { name: "Tomil Trust Limited", email: "" },
  { name: "Topmost Securities Limited", email: "topmostsec@yahoo.com" },
  { name: "Tower Asset Management Limited", email: "info@towerassetsonline.net" },
  { name: "Tower Securities & Investment Company Limited", email: "info@towersecng.com" },
  { name: "Trade Link Securities Limited", email: "info@tradelinksecurities.com.ng" },
  { name: "Traders Trust & Investment Co. Limited", email: "info@traderstrustltd.com" },
  { name: "Transworld Investment & Securities Limited", email: "investment@transworldltd.com.ng" },
  { name: "Trust Yield Investment Limited", email: "" },
  { name: "TrustBanc Capital Management Limited", email: "info@trustbancgroup.com" },
  { name: "Trusthouse Investments Limited", email: "info@trusthouseng.com" },
  { name: "TRW Stockbrokers Limited", email: "info@trw-stockbrokers.com.ng" },
  { name: "Tyndale Investment Limited", email: "" }, // VERIFY: source text was too small/unclear to transcribe confidently
  { name: "UCML Capital/Innova Securities", email: "info@innovasecuritiesltd.com" },
  { name: "UIDC Securities Limited", email: "" },
  { name: "UPEX Capital Limited", email: "" },
  { name: "United Capital Securities Limited", email: "cec@unitedcapitalplcgroup.com" },
  { name: "Valmon Securities Limited", email: "info@valmonsecurities.com" },
  { name: "Valueline Securities & Investment Limited", email: "" },
  { name: "Vetiva Securities Limited", email: "assetmanagement@vetiva.com" },
  { name: "Vision Trust & Investment Limited", email: "" },
  { name: "WCM Capital Limited", email: "info@woodlandcapitalplc.com" },
  { name: "WSTC Securities Limited", email: "info@wstc.com.ng" },
  { name: "Yuderb Investments & Securities Limited (now Novambl Securities)", email: "info@novambl.com" },
  { name: "Zion Stockbrokers & Securities Limited", email: "stockmails@zionstockbrokers.com" },
];
